### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by accordingtoherr** [ehowey/gatsby-starter-catalyst-hydrogen#11]
Hi it looks like the docs for this - they are not loading for me wanted to flag it

**Comment by ehowey** [comment]
Were you going here: https://www.gatsbycatalyst.com/docs/

? Maybe I have a broken link!  Thanks for the heads up.  Can you say more about where you were trying to get the docs from?

**Comment by ehowey** [comment]
Also let me know if you run into any problems and I would be happy to help!

**Comment by accordingtoherr** [comment]
Hey there! And I was but the hydrogen doc doesn’t seem to load. I clicked on it and maybe the link is broken ? The other docs look fine but that happens to be the one I’m looking for

**Comment by ehowey** [comment]
Odd - loading for me now. I have been working on it a bit lately so maybe there was some kind of weird temporary cache invalidation issue.

Can you let me know if you can see these links okay now:

https://www.gatsbycatalyst.com/docs/gatsby-theme-catalyst-hydrogen
and
https://www.gatsbycatalyst.com/docs/tutorials/building-a-website-for-a-freelance-writer-using-gatsby-theme-catalyst-hydrogen

**Comment by accordingtoherr** [comment]
Perfect loads for me only one ther doesn’t is the tutorial doc in hydrogen

**Comment by accordingtoherr** [comment]
Not urgent! Just wanted to flag that so I can work on my project tomorrow no rush

**Comment by ehowey** [comment]
Thank-you!  Broken link! I had a capital B in there. Ugh!

I am going to close this now but I really appreciate you letting me know that! If you get stuck tommorow or need help let me know.

**Comment by accordingtoherr** [comment]
Thanks Eric and no problem happy I could help!
